name: shop_core
description: shop domain
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  equatable: ^2.0.3
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.2.0
  test: ^1.21.4