name: objectbox_tutorial
description: Flutter ObjectBox Tutorial
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.3

dependencies:
  bloc: ^8.0.2
  faker: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  object_box:
    path: packages/object_box
  provider: ^6.0.0
  shop_core:
    path: packages/shop_core
  shop_order_repository:
    path: packages/shop_order_repository

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true