name: objectbox_tutorial
description: Flutter ObjectBox Tutorial
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.3

dependencies:
  flutter:
    sdk: flutter
  objectbox: ^1.6.2
  objectbox_sync_flutter_libs: any
  path_provider: ^2.0.11
  faker: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.3.2
  objectbox_generator: any

flutter:
  uses-material-design: true
  generate: true