name: object_box
description: Local database
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  objectbox: ^1.6.2
  objectbox_sync_flutter_libs: any
  path_provider: ^2.0.11

dev_dependencies:
  build_runner: 2.3.2
  objectbox_generator: any