name: shop_order_repository
description: manage shop orders
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  equatable: ^2.0.3
  shop_core:
    path: ../shop_core
  object_box:
    path: ../object_box

dev_dependencies:
  build_runner: ^2.2.0
  test: ^1.21.4